allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  cpu-features: set this to true or false
  prisma: true
  protobufjs: set this to true or false
  ssh2: set this to true or false
  unrs-resolver: true
