// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from 'dotenv';
import { defineConfig } from 'prisma/config';

// 앱 런타임(app.module.ts)과 동일하게 .env.${NODE_ENV} 우선 로드 후 .env로 폴백
loadEnv({ path: `.env.${process.env.NODE_ENV ?? 'development'}` });
loadEnv();

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
