/**
 * 프로젝트 전역 에러 코드 카탈로그.
 * 새 에러를 추가할 때는 이 파일에 코드를 먼저 등록하고,
 * 도메인별 예외 파일에서 해당 코드를 참조해 클래스를 정의한다.
 */
export const ErrorCode = {
  // Auth
  AUTH_INVALID_GOOGLE_TOKEN: 'AUTH_INVALID_GOOGLE_TOKEN',
  AUTH_INVALID_TOKEN_TYPE: 'AUTH_INVALID_TOKEN_TYPE',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',

  // Task
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_INVALID_STATE: 'TASK_INVALID_STATE',
  TASK_BIG3_LIMIT_EXCEEDED: 'TASK_BIG3_LIMIT_EXCEEDED',
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  FOLDER_NAME_DUPLICATED: 'FOLDER_NAME_DUPLICATED',

  // Calendar link (Google Calendar 통합)
  CALENDAR_OAUTH_STATE_INVALID: 'CALENDAR_OAUTH_STATE_INVALID',
  CALENDAR_OAUTH_CODE_EXCHANGE_FAILED: 'CALENDAR_OAUTH_CODE_EXCHANGE_FAILED',
  CALENDAR_INTEGRATION_NOT_FOUND: 'CALENDAR_INTEGRATION_NOT_FOUND',
  CALENDAR_NOT_SUBSCRIBED: 'CALENDAR_NOT_SUBSCRIBED',
  CALENDAR_GOOGLE_API_ERROR: 'CALENDAR_GOOGLE_API_ERROR',
  CALENDAR_TOKEN_REFRESH_FAILED: 'CALENDAR_TOKEN_REFRESH_FAILED',
  CALENDAR_WEBHOOK_UNKNOWN_CHANNEL: 'CALENDAR_WEBHOOK_UNKNOWN_CHANNEL',

  // Device
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',

  // Canvas
  CANVAS_NOT_FOUND: 'CANVAS_NOT_FOUND',
  CANVAS_VERSION_TOKEN_INVALID: 'CANVAS_VERSION_TOKEN_INVALID',
  CANVAS_VERSION_TOKEN_EXPIRED: 'CANVAS_VERSION_TOKEN_EXPIRED',
  CANVAS_UPLOAD_NOT_CONFIRMED: 'CANVAS_UPLOAD_NOT_CONFIRMED',
  CANVAS_FILE_TOO_LARGE: 'CANVAS_FILE_TOO_LARGE',

  // OCR
  OCR_TOKEN_INVALID: 'OCR_TOKEN_INVALID',
  OCR_TOKEN_EXPIRED: 'OCR_TOKEN_EXPIRED',
  OCR_IMAGE_INVALID_TYPE: 'OCR_IMAGE_INVALID_TYPE',
  OCR_IMAGE_EMPTY: 'OCR_IMAGE_EMPTY',
  OCR_IMAGE_TOO_LARGE: 'OCR_IMAGE_TOO_LARGE',

  // Common
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
